version: '3'
services:
  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    ports:
     - 8080:8080
     - 50000:50000
    volumes:
     - jenkins-data:/var/jenkins_home

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
     - 8081:8081
    volumes:
     - artifactory-data:/var/opt/jfrog/artifactory

  sonarqube:
   image: sonarqube:7.0-alpine
   ports:
    - 9000:9000
    - 9092:9092

volumes:
 jenkins-data:
 artifactory-data: